-- add product iPhone priced at $200.
INSERT INTO Products VALUES ('iPhone', 200.0);

-- add customer Tina Smith.
INSERT INTO Customers VALUES (
	'Tina', 
	'Smith', 
	'6011606879436549');

-- create order for Tina Smith bought an iPhone.
INSERT INTO Orders VALUES (
	(SELECT TOP 1 ID FROM Products WHERE ProductName = 'iPhone'),
	(SELECT TOP 1 ID FROM Customers WHERE FirstName = 'Tina');

-- report all orders by Tina Smith.
SELECT * FROM Orders as o INNER JOIN Customers as c on o.CustomerID = c.ID
	WHERE c.FirstName = 'Tina';

-- report all revenue generated by sales of iPhone. 
SELECT p.ProductName, SUM(p.Price) as 'Price' FROM Products as p 
	INNER JOIN Orders as o on o.ProductID = p.ID
		WHERE p.ProductName = 'iPhone'
		GROUP BY p.Productname;

-- increase the price of iPhone to $250
UPDATE Products
SET Price = 250.0
WHERE ProductName = 'iPhone';

select * from Customers;