//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetDogServiceClient.GetDogService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetDogService.IGetDogService")]
    public interface IGetDogService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDogService/GetDog", ReplyAction="http://tempuri.org/IGetDogService/GetDogResponse")]
        string GetDog();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDogService/GetDog", ReplyAction="http://tempuri.org/IGetDogService/GetDogResponse")]
        System.Threading.Tasks.Task<string> GetDogAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDogService/GetDogs", ReplyAction="http://tempuri.org/IGetDogService/GetDogsResponse")]
        string GetDogs(int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDogService/GetDogs", ReplyAction="http://tempuri.org/IGetDogService/GetDogsResponse")]
        System.Threading.Tasks.Task<string> GetDogsAsync(int count);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetDogServiceChannel : GetDogServiceClient.GetDogService.IGetDogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDogServiceClient : System.ServiceModel.ClientBase<GetDogServiceClient.GetDogService.IGetDogService>, GetDogServiceClient.GetDogService.IGetDogService {
        
        public GetDogServiceClient() {
        }
        
        public GetDogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetDogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDog() {
            return base.Channel.GetDog();
        }
        
        public System.Threading.Tasks.Task<string> GetDogAsync() {
            return base.Channel.GetDogAsync();
        }
        
        public string GetDogs(int count) {
            return base.Channel.GetDogs(count);
        }
        
        public System.Threading.Tasks.Task<string> GetDogsAsync(int count) {
            return base.Channel.GetDogsAsync(count);
        }
    }
}
